ansible_user: root

domain_name: us-inst1.enderhost.online
instance_ip: "159.65.251.212"
ansible_python_interpreter: /usr/bin/python3

# ROLE: VPN-CLIENT

vpn_instance_ip: "10.13.13.11"
# vpn_client_private_key: ""
# vpn_client_preshared_key: ""