ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_ed25519

domain_name: nyc3-node-1.ynoacamino.me
instance_ip: "143.198.7.55"
ansible_python_interpreter: /usr/bin/python3

# ROLE: VPN-CLIENT

vpn_instance_ip: "10.13.13.15"
# vpn_client_private_key: ""
# vpn_client_preshared_key: "