kube_master_ufw_rules:
  - { port: 6443, proto: "tcp" }
  - { port: 10250, proto: "tcp" }
  - { port: 8472, proto: "udp" }

headscale_traefik_enabled: true
headscale_traefik_network: "traefik-net"
headscale_traefik_certresolver: "dnsresolver"

tailscale_advertise_routes: "10.42.0.0/16,10.43.0.0/16"

