ansible_user: root

domain_name: template-inst.enderhost.online
instance_ip: "111.111.111.109"
ansible_python_interpreter: /usr/bin/python3


# ROLE: VPN-CLIENT

vpn_instance_ip: "10.8.0.0"
# vpn_client_private_key: ""
# vpn_client_preshared_key: ""