ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_ed25519

domain_name: nyc1-node-2.ynoacamino.me
instance_ip: "198.211.102.187"
ansible_python_interpreter: /usr/bin/python3

# ROLE: VPN-CLIENT

vpn_instance_ip: "10.13.13.12"
# vpn_client_private_key: ""
# vpn_client_preshared_key: ""