- name: Restart traefik
  community.docker.docker_compose_v2:
    project_src: /opt/traefik
    state: restarted

- name: Wait for dns propagation
  ansible.builtin.pause:
    seconds: 30
    prompt: "Waiting for DNS to stabilize before restarting Traefik..."

- name: Restart traefik for certificate generation
  community.docker.docker_compose_v2:
    project_src: /opt/traefik
    state: absent
    remove_volumes: true

- name: Start traefik after certificate cleanup
  community.docker.docker_compose_v2:
    project_src: /opt/traefik
    state: present
