essential_packages:
  - htop
  - micro
  - git
  - curl
  - wget
  - unzip
  - net-tools
  - ufw
  - just

timezone: America/Lima

ufw_rules:
  - { port: 22, proto: "tcp" }
  - { port: 80, proto: "tcp" }
  - { port: 443, proto: "tcp" }
  - { port: 4443, proto: "tcp" }

headscale_server_url: "https://headscale-kube.ynoacamino.me:4443"
headscale_base_domain: "kube.ynoacamino.me"
headscale_traefik_domain: "headscale-kube.ynoacamino.me"
headscale_ipv4_prefix: "100.64.0.0/10"
headscale_ipv6_prefix: "fd7a:115c:a1e0::/48"


tailscale_args: "--accept-routes --accept-dns=true"
tailscale_up_skip: false

