- name: Restart Portainer
  community.docker.docker_compose_v2:
    project_src: "/opt/monitoring/portainer"
    state: restarted

- name: Restart Node Exporter
  community.docker.docker_compose_v2:
    project_src: "/opt/monitoring/node_exporter"
    state: restarted

- name: Restart cAdvisor
  community.docker.docker_compose_v2:
    project_src: "/opt/monitoring/cadvisor"
    state: restarted
