- name: Initialize Kube Node VPS
  hosts: kube_nodes
  become: true

  roles:
    - role: geerlingguy.docker
    - role: swap

  tasks:
    - name: Update package list
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade all installed packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: true

    - name: Install essential packages
      ansible.builtin.apt:
        name: "{{ essential_packages }}"
        state: present

    - name: Set timezone to UTC
      community.general.timezone:
        name: "{{ timezone }}"

    - name: Configure UFW rules
      community.general.ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      loop: "{{ ufw_rules }}"

    - name: Enable UFW
      community.general.ufw:
        state: enabled
